name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and Push Docker Images
        run: |
          docker-compose build
          docker-compose push
  deploy:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-53-35-38.eu-north-1.compute.amazonaws.com << 'EOF'
            # Add the user to the docker group
            sudo usermod -aG docker ubuntu
            # Reboot to apply the group change
            sudo reboot
          EOF

      - name: Wait for EC2 to Reboot
        run: |
          sleep 60

      - name: Continue Deployment
        run: |
          ssh -o StrictHostKeyChecking=no ubuntu@ec2-13-53-35-38.eu-north-1.compute.amazonaws.com << 'EOF'
            # Clone the repository and checkout the latest commit
            cd /home/ubuntu
            if [ -d my-docker-compose-project ]; then
              rm -rf my-docker-compose-project
            fi
            git clone https://github.com/${{ github.repository }}.git my-docker-compose-project
            cd my-docker-compose-project
            git checkout ${{ github.sha }}
          
            # Run Docker Compose
            sudo docker-compose pull
            sudo docker-compose up -d --remove-orphans
            sudo docker system prune -af
          EOF